### ISSUE TITLE
org.netbeans.api:org-openide-util:RELEASE80 dependency

### ISSUE THREAD

**Issue by ivanpopelyshev** [timboudreau/netty-http-client#8]
failed to retrieve dependencides with gradle;

```groovy
dependencies {
    compile group: 'com.mastfrog', name: 'netty-http-client', version: '1.6.2'
}
repositories {
    maven {
       url "http://timboudreau.com/builds/plugin/repository/everything/"
    }
}
```

My Project > com.mastfrog:netty-http-client:1.6.2 > com.mastfrog:url:1.6.2 > Could not find org.netbeans.api:org-openide-util:RELEASE80.

**Comment by timboudreau** [comment]
You need another Maven repository - http://bits.netbeans.org/maven2/ - it is in the repositories list in the `pom.xml`.

**Comment by ivanpopelyshev** [comment]
Thank you.
